"""split name to first_name last_name and add new models

Revision ID: 3d0b5148ba6c
Revises: 4032a22d3219
Create Date: 2026-02-27 03:09:48.770427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0b5148ba6c'
down_revision = '4032a22d3219'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add new columns as NULLABLE first (MSSQL requires this for non-empty tables)
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=60), nullable=True))

    # Step 2: Populate from existing 'name' column
    # Split "First Last" into first_name and last_name
    op.execute("""
        UPDATE [user]
        SET first_name = CASE
                WHEN CHARINDEX(' ', name) > 0 THEN LEFT(name, CHARINDEX(' ', name) - 1)
                ELSE name
            END,
            last_name = CASE
                WHEN CHARINDEX(' ', name) > 0 THEN SUBSTRING(name, CHARINDEX(' ', name) + 1, LEN(name))
                ELSE ''
            END
    """)

    # Step 3: Make columns NOT NULL now that they have data
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name', existing_type=sa.String(length=60), nullable=False)
        batch_op.alter_column('last_name', existing_type=sa.String(length=60), nullable=False)

    # Step 4: Drop old name column
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
