"""Final update for all features

Revision ID: 83dc6ea945a2
Revises: f427a6e86bf3
Create Date: 2025-12-04 15:40:07.617094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dc6ea945a2'
down_revision = 'f427a6e86bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_unavailable_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car_unavailable_date', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_unavailable_date_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_unavailable_date_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_unavailable_date_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_unavailable_date', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_unavailable_date_start_date'))
        batch_op.drop_index(batch_op.f('ix_car_unavailable_date_end_date'))
        batch_op.drop_index(batch_op.f('ix_car_unavailable_date_car_id'))

    op.drop_table('car_unavailable_date')
    # ### end Alembic commands ###
