"""Initial models with all features and indexes

Revision ID: d8ee47b4bedc
Revises: 
Create Date: 2025-11-12 11:09:16.154310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ee47b4bedc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('id_image', sa.String(length=255), nullable=True),
    sa.Column('id_updated_at', sa.DateTime(), nullable=True),
    sa.Column('license_image', sa.String(length=255), nullable=True),
    sa.Column('license_updated_at', sa.DateTime(), nullable=True),
    sa.Column('passport_image', sa.String(length=255), nullable=True),
    sa.Column('residence_proof_image', sa.String(length=255), nullable=True),
    sa.Column('job_proof_image', sa.String(length=255), nullable=True),
    sa.Column('selfie_image', sa.String(length=255), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('agreed_to_terms', sa.Boolean(), nullable=True),
    sa.Column('agreed_to_privacy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('insurance_details', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_price_per_day'), ['price_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_year'), ['year'], unique=False)

    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_user_id'), ['user_id'], unique=False)

    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_renter_id'), ['renter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_status'))
        batch_op.drop_index(batch_op.f('ix_booking_start_date'))
        batch_op.drop_index(batch_op.f('ix_booking_renter_id'))
        batch_op.drop_index(batch_op.f('ix_booking_end_date'))
        batch_op.drop_index(batch_op.f('ix_booking_car_id'))

    op.drop_table('booking')
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_user_id'))
        batch_op.drop_index(batch_op.f('ix_otp_expires_at'))

    op.drop_table('otp')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_year'))
        batch_op.drop_index(batch_op.f('ix_car_status'))
        batch_op.drop_index(batch_op.f('ix_car_price_per_day'))
        batch_op.drop_index(batch_op.f('ix_car_owner_id'))
        batch_op.drop_index(batch_op.f('ix_car_model'))
        batch_op.drop_index(batch_op.f('ix_car_brand'))

    op.drop_table('car')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_approval_status'))

    op.drop_table('user')
    # ### end Alembic commands ###
